version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: supplychain
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/supplychain
      JWT_SECRET: your_jwt_secret
      # Add SMTP and other env vars as needed
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
    command: npm start

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:4000/api/v1
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/app

volumes:
  db_data: 