// Zephyr Cloud Configuration
// This file contains the configuration for deploying to Zephyr Cloud

module.exports = {
  // Your Zephyr Cloud project configuration
  project: {
    name: 'react-native-super-app',
    description: 'React Native Super App with Module Federation',
  },
  
  // Host App Configuration
  host: {
    name: 'HostApp',
    path: './HostApp',
    entry: './index.js',
  },
  
  // Mini Apps Configuration
  miniApps: [
    {
      name: 'UserProfileApp',
      path: './MiniApp1',
      entry: './index.js',
      port: 9001,
    },
    {
      name: 'ShoppingCartApp', 
      path: './MiniApp2',
      entry: './index.js',
      port: 9002,
    },
    {
      name: 'SettingsApp',
      path: './MiniApp3', 
      entry: './index.js',
      port: 9003,
    },
  ],
  
  // Shared Dependencies
  shared: {
    react: {
      singleton: true,
      version: '18.3.1',
      eager: true,
    },
    'react-native': {
      singleton: true,
      version: '0.75.4', 
      eager: true,
    },
    '@react-navigation/native': {
      singleton: true,
      eager: true,
    },
    '@react-navigation/native-stack': {
      singleton: true,
      eager: true,
    },
    '@react-navigation/bottom-tabs': {
      singleton: true,
      eager: true,
    },
    'react-native-safe-area-context': {
      singleton: true,
      eager: true,
    },
    'react-native-screens': {
      singleton: true,
      eager: true,
    },
    'react-native-vector-icons': {
      singleton: true,
      eager: true,
    },
  },
  
  // Build Configuration
  build: {
    platforms: ['ios', 'android'],
    mode: 'production',
    outputPath: './dist',
  },
  
  // Deployment Configuration
  deployment: {
    // Environment-specific URLs will be auto-generated by Zephyr
    staging: {
      enabled: true,
    },
    production: {
      enabled: true,
    },
  },
};